# Generated by Django 3.0.2 on 2020-02-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('today', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='gender',
            field=models.CharField(choices=[('1', 'male'), ('2', 'female'), ('3', 'intersex')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
