# Generated by Django 3.0.2 on 2020-02-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('today', '0002_reporter_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='city',
            field=models.CharField(blank=True, choices=[('London', 'London'), ('kenya', 'Kenya'), ('uganda', 'Uganda')], max_length=20),
        ),
    ]
