# Generated by Django 3.0.2 on 2020-02-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('today', '0003_reporter_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mytest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.ManyToManyField(to='today.Reporter')),
            ],
        ),
    ]
