# Generated by Django 3.0.2 on 2020-02-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('today', '0005_auto_20200228_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('gender', models.CharField(choices=[('1', 'male'), ('2', 'female'), ('3', 'intersex')], max_length=1)),
            ],
        ),
    ]
