# Generated by Django 3.0.2 on 2020-03-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('today', '0007_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('videofile', models.FileField(null=True, upload_to='videos', verbose_name='')),
            ],
        ),
    ]
