# Generated by Django 3.0.2 on 2020-03-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('today', '0011_remove_postproblem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postproblem',
            name='image',
            field=models.ImageField(default='', upload_to='post_pics'),
            preserve_default=False,
        ),
    ]
