# Generated by Django 3.0.2 on 2020-03-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('today', '0012_postproblem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postproblem',
            name='file',
            field=models.FileField(default='', upload_to='files'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postproblem',
            name='image',
            field=models.ImageField(upload_to='post_pics', verbose_name=models.FileField(upload_to='files')),
        ),
    ]
