# Generated by Django 3.0.2 on 2020-03-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200228_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': None},
        ),
        migrations.AddField(
            model_name='membership',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
